name             'lita'
maintainer       'Harlan Barnes'
maintainer_email 'hbarnes@pobox.com'
license          'Apache 2.0'
description      'Installs/configures the Lita chatbot'
long_description 'Installs/configures the Lita chatbot'
version          '1.0.5'

supports 'ubuntu'
supports 'centos', '>= 7.1'

depends 'runit'
depends 'apt'
depends 'build-essential'
depends 'ruby-ng', '~> 0.1.1'
depends 'redis2', '~> 0.5.0'
